version: '3.5'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        env_file: .env
        working_dir: /var/www
        container_name: api-php
        volumes:
          - ./:/var/www
        networks:
          - db-net
    mongo:
      image: mongo:5.0
      container_name: mongo
      environment:
        - MONGO_INITDB_ROOT_USERNAME=
        - MONGO_INITDB_ROOT_PASSWORD=
      expose:
        - 27017
      ports:
        - "27017:27017"
      volumes:
        - ./database/mongodb/db:/data/db
        - ./database/mongodb/dev.archive:/Databases/dev.archive
        - ./database/mongodb/production:/Databases/production
    
    #Nginx Service
    webserver:
      image: nginx:alpine
      container_name: webserver
      restart: unless-stopped
      tty: true
      ports:
        - "80:80"
      volumes:
        - ./:/var/www
        - ./nginx/conf.d/:/etc/nginx/conf.d/
      networks:
        - db-net
networks:
  db-net:
    external:
      name: db_network